# Generated by Django 3.2.8 on 2021-11-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_certificate_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['name'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
